import { MenuItem } from './menu.model';

export const MENU: MenuItem[] = [
  {
    id: 1,
    label: 'global.menu.title',
    isTitle: true,
  },
  {
    id: 2,
    label: 'global.menu.home',
    icon: 'bx-home-circle',
  },
  {
    id: 3,
    label: 'global.menu.entities.main',
    isTitle: true,
  },
  {
    id: 5,
    label: 'global.menu.entities.sector',
    icon: 'bx-pie-chart-alt',
    link: '/sector',
  },
  {
    id: 6,
    label: 'global.menu.entities.downgrading',
    icon: 'bx-sort-down',
    link: '/downgrading',
  },
  {
    id: 7,
    label: 'global.menu.entities.reject',
    icon: 'bx-unlink',
    link: '/reject',
  },
  {
    id: 8,
    label: 'global.menu.entities.client',
    icon: 'bx-meh',
    link: '/client',
  },
  {
    id: 9,
    label: 'global.menu.entities.compte',
    icon: 'bx-user',
    link: '/compte',
  },
  {
    id: 10,
    label: 'global.menu.entities.engagement',
    icon: 'bx-user',
    link: '/engagement',
  },
  {
    id: 11,
    label: 'global.menu.entities.task',
    icon: 'bx-user',
    link: '/task',
  },
  {
    id: 12,
    label: 'global.menu.admin.main',
    isTitle: true,
    isAdmin: true,
  },
  {
    id: 13,
    label: 'global.menu.admin.userManagement',
    icon: 'bx-user-plus',
    link: '/admin/user-management',
    isAdmin: true,
  },
  {
    id: 14,
    label: 'global.menu.entities.employe',
    icon: 'bx-user',
    link: '/admin/employe',
  },
  {
    id: 15,
    label: 'global.menu.entities.entite',
    icon: 'bx-user',
    link: '/admin/entite',
  },
  {
    id: 16,
    label: 'global.menu.entities.typeEntite',
    icon: 'bx-user',
    link: '/admin/type-entite',
  },
  {
    id: 17,
    label: 'global.menu.entities.scoring',
    icon: 'bx-football',
    link: '/scoring',
  },
  {
    id: 18,
    label: 'global.menu.entities.downgradingStep',
    icon: 'bx-sort-down',
    link: '/downgrading-step',
  },
  {
    id: 19,
    label: 'global.menu.entities.rejectType',
    icon: 'bx-unlink',
    link: '/reject-type',
  },
  {
    id: 20,
    label: 'global.menu.entities.engagementType',
    icon: 'bx-user',
    link: '/engagement-type',
  },
  {
    id: 21,
    label: 'global.menu.entities.status',
    icon: 'bx-user',
    link: '/status',
  },
  {
    id: 22,
    label: 'global.menu.entities.taskType',
    icon: 'bx-user',
    link: '/task-type',
  },
  {
    id: 26,
    label: 'global.menu.entities.action',
    icon: 'bx-user',
    link: '/action',
  },
  {
    id: 24,
    label: 'global.menu.admin.metrics',
    icon: 'bx-tachometer',
    link: '/admin/metrics',
    isAdmin: true,
  },
  {
    id: 25,
    label: 'global.menu.admin.health',
    icon: 'bx-heart',
    link: '/admin/health',
    isAdmin: true,
  },
  {
    id: 26,
    label: 'global.menu.admin.configuration',
    icon: 'bx-cog',
    link: '/admin/configuration',
    isAdmin: true,
  },
  {
    id: 27,
    label: 'global.menu.admin.audits',
    icon: 'bx-bell',
    link: '/admin/audits',
    isAdmin: true,
  },
  {
    id: 28,
    label: 'global.menu.admin.logs',
    icon: 'bx-save',
    link: '/admin/logs',
    isAdmin: true,
  },
  {
    id: 29,
    label: 'global.menu.admin.apidocs',
    icon: 'bx-book',
    link: '/admin/docs',
    isAdmin: true,
  },
];
